### PR TITLE
numpy/numba versioning incompatibility

### PR DESCRIPTION
**Pull request by micheleangelofabbri**
Temp correction to numpy/numba versioning incompatibility

### CODE REVIEW

**Comment by berkgercek** [comment]
Hey @micheleangelofabbri , what causes the versioning incompatibility? Numba requiring an older version of numpy? I haven't seen an issue when building my env recently but that was a few weeks ago.

**Comment by micheleangelofabbri** [comment]
Hey Berk, 
On the numba v0.54.1 project [page](https://pypi.org/project/numba/0.54.1/), there are the following dependencies:
- Python versions: 3.7-3.9
- llvmlite 0.37.*
- NumPy >=1.17,<1.21 (can build with 1.11 for ABI compatibility).

**Comment by berkgercek** [comment]
Ah ok, I see. Thanks for clarifying!

**Comment by micheleangelofabbri** [comment]
As it turns out, this change is unwarranted as anaconda handles this conflict quite seamlessly (unlike pip).

**Pull request closed without merging**
